### ISSUE TITLE
This works for content inside an iframe?

### ISSUE THREAD

**Issue by ghost** [kethinov/nw.js-external-linker#1]
Hello Kethinov, I was building a javascript plugin to do the same thing as yours, I was wondering if your code can ( is that even possible ? ), to add the EventListener to a click inside an iframe?

Thank you in advance.

**Comment by kethinov** [comment]
There is no direct way to do that. There are [indirect ways](https://gist.github.com/jaydson/1780598), but none I know of would allow this plugin to override links in iframes the way it does for other links.

If your goal is to prevent iframes from being a security risk, then NW.js does provide a way to add iframes to your app [in a secure way](https://github.com/nwjs/nw.js/wiki/Security).

**Comment by ghost** [comment]
Thanks a lot for your time and help! :smile:
